version: "3.9"

services:
  fastapi:
    build: .
    container_name: mailbook_backend
    ports:
      - "${PORT:-8002}:${PORT:-8002}"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - mailbook-backend-net

  postgres:
    image: postgres:17-alpine
    container_name: mailbook_backend_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-mailbook_backend}
    ports:
      - "${POSTGRES_HOST_PORT:-5435}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mailbook-backend-net

  redis:
    image: redis:8.2
    container_name: mailbook_backend_redis
    restart: unless-stopped
    ports:
      - "${REDIS_HOST_PORT:-6381}:6379"
    volumes:
      - redis_data:/data
    networks:
      - mailbook-backend-net

volumes:
  postgres_data:
  redis_data:

networks:
  mailbook-backend-net:
    driver: bridge
