"""add payment_events email_id unique

Revision ID: 7476a570439e
Revises: fd60fc881b8e
Create Date: 2026-05-06 10:16:11.618175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7476a570439e'
down_revision: Union[str, Sequence[str], None] = 'fd60fc881b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_payment_events_email_id', 'payment_events', ['email_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_events_email_id', 'payment_events', type_='unique')
    # ### end Alembic commands ###
